import { z } from "zod";

// Every path under data/jobs/ is built from an id created here, never from
// anything a request carries. Requests may only echo an id back, and every
// route re-checks it against this pattern before it touches the file system.
export const JOB_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export function createJobId(): string {
  return crypto.randomUUID();
}

export function isJobId(value: unknown): value is string {
  return typeof value === "string" && JOB_ID_PATTERN.test(value);
}

export const jobIdSchema = z.string().regex(JOB_ID_PATTERN);

export type SourceType = "pptx" | "pdf" | "png" | "jpg";
export type JobKind = "pptx" | "pdf" | "images";

// Hard ceilings for the stored job description. The configured MAX_SLIDES is a
// lower, user-facing limit; these only stop a corrupted job.json from growing
// without bound.
const MAX_STORED_FILES = 1000;
const MAX_STORED_SLIDES = 1000;

export const DEFAULT_MAX_UPLOAD_MB = 50;
export const DEFAULT_MAX_SLIDES = 40;

export type Limits = { maxUploadBytes: number; maxSlides: number };

export function limitsFromEnv(env: Record<string, string | undefined>): Limits {
  const megabytes = positiveInteger(env.MAX_UPLOAD_MB, DEFAULT_MAX_UPLOAD_MB, 500);
  const slides = positiveInteger(env.MAX_SLIDES, DEFAULT_MAX_SLIDES, MAX_STORED_SLIDES);
  return { maxUploadBytes: megabytes * 1024 * 1024, maxSlides: slides };
}

function positiveInteger(raw: string | undefined, fallback: number, max: number): number {
  const value = Number(raw);
  if (!Number.isInteger(value) || value < 1 || value > max) return fallback;
  return value;
}

// Magic bytes, because an extension proves nothing. PPTX is a ZIP, so "pptx"
// here only means "a ZIP that might be one"; readPptx verifies the parts.
const SIGNATURES: ReadonlyArray<{ type: SourceType; bytes: readonly number[] }> = [
  { type: "png", bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  { type: "jpg", bytes: [0xff, 0xd8, 0xff] },
  { type: "pdf", bytes: [0x25, 0x50, 0x44, 0x46, 0x2d] },
  { type: "pptx", bytes: [0x50, 0x4b, 0x03, 0x04] },
];

export const SIGNATURE_BYTES = 8;

export function detectType(head: Uint8Array): SourceType | null {
  for (const signature of SIGNATURES) {
    if (signature.bytes.every((byte, index) => head[index] === byte)) return signature.type;
  }
  return null;
}

// The stored name is ours; the uploaded name survives as display data only.
export function storedFileName(index: number, type: SourceType): string {
  return `${String(index).padStart(3, "0")}.${type}`;
}

export function slideFileName(index: number): string {
  return `${String(index).padStart(3, "0")}.png`;
}

export function detectionFileName(index: number): string {
  return `${String(index).padStart(3, "0")}.json`;
}

/** The export always has the same name on disk; the download route renames it. */
export const OUTPUT_FILE = "deck.pptx";

export function notesFileName(index: number): string {
  return `${String(index).padStart(3, "0")}.txt`;
}

export type JobFolder = "source" | "slides" | "notes" | "detect" | "output";

const JOB_FOLDERS: ReadonlyArray<JobFolder> = ["source", "slides", "notes", "detect", "output"];
// Detection answers are stored per slide as JSON, the export as one file whose
// name is generated here; a display name never reaches the file system.
const JOB_FILE_PATTERN = /^(\d{3}\.(pptx|pdf|png|jpg|txt|json)|deck\.pptx)$/;

// The single gate between a job id and the file system. It throws instead of
// returning null so a forgotten check is a crash, not a traversal. Everything
// it accepts was generated by this module in the first place.
export function jobPathSegments(id: string, folder?: JobFolder, file?: string): string[] {
  if (!isJobId(id)) throw new Error("invalid job id");
  const segments = [id];
  if (folder !== undefined) {
    if (!JOB_FOLDERS.includes(folder)) throw new Error("invalid job folder");
    segments.push(folder);
  }
  if (file !== undefined) {
    if (folder === undefined) throw new Error("a job file needs a folder");
    if (!JOB_FILE_PATTERN.test(file)) throw new Error("invalid job file name");
    segments.push(file);
  }
  return segments;
}

export function sanitizeDisplayName(raw: string): string {
  // Control characters could break a log line or a terminal; separators could
  // make the name read like a path in the UI. Neither is ever used as a path.
  const cleaned = raw
    .replace(/[\p{Cc}\p{Cf}]/gu, "")
    .replace(/[\\/]+/g, " ")
    .trim()
    .slice(0, 120);
  return cleaned.length > 0 ? cleaned : "unnamed file";
}

export type MixResult =
  | { ok: true; kind: JobKind }
  | { ok: false; reason: "empty" | "mixed-types" | "too-many-files" | "too-many-images" };

export function planJobKind(types: readonly SourceType[], limits: Limits): MixResult {
  if (types.length === 0) return { ok: false, reason: "empty" };
  const unique = new Set(types);
  if (unique.has("pptx") || unique.has("pdf")) {
    if (unique.size > 1) return { ok: false, reason: "mixed-types" };
    if (types.length > 1) return { ok: false, reason: "too-many-files" };
    return { ok: true, kind: types[0] === "pptx" ? "pptx" : "pdf" };
  }
  if (types.length > limits.maxSlides) return { ok: false, reason: "too-many-images" };
  return { ok: true, kind: "images" };
}

// "slide-2" must come before "slide-10", and digit runs are compared as numbers
// rather than parsed, so a 40-digit name cannot overflow.
export function compareNatural(a: string, b: string): number {
  const chunks = /(\d+)|(\D+)/g;
  const left = a.toLowerCase().match(chunks) ?? [];
  const right = b.toLowerCase().match(chunks) ?? [];
  for (let index = 0; index < Math.min(left.length, right.length); index += 1) {
    const one = left[index];
    const other = right[index];
    const bothNumeric = /^\d/.test(one) && /^\d/.test(other);
    if (bothNumeric) {
      const trimmedOne = one.replace(/^0+(?=\d)/, "");
      const trimmedOther = other.replace(/^0+(?=\d)/, "");
      if (trimmedOne.length !== trimmedOther.length) {
        return trimmedOne.length - trimmedOther.length;
      }
      if (trimmedOne !== trimmedOther) return trimmedOne < trimmedOther ? -1 : 1;
      continue;
    }
    if (one !== other) return one < other ? -1 : 1;
  }
  return left.length - right.length;
}

export function sortImageNames(names: readonly string[]): string[] {
  return [...names].sort(compareNatural);
}

export const sourceFileSchema = z
  .object({
    file: z.string().regex(/^\d{3}\.(pptx|pdf|png|jpg)$/),
    name: z.string().max(120),
    type: z.enum(["pptx", "pdf", "png", "jpg"]),
    bytes: z.number().int().nonnegative(),
  })
  .strict();

/** What happened to one slide's detection, so a retry knows what to redo. */
export const DETECTION_STATUSES = ["done", "failed", "skipped"] as const;

export const detectionSchema = z
  .object({
    status: z.enum(DETECTION_STATUSES),
    /** A short code, never a message from an exception or from Gemini. */
    reason: z.string().max(40).nullable(),
    /** Blocks kept after validation, for the per-slide line on the page. */
    blocks: z.number().int().nonnegative(),
    /** True when the answer came from the development cache, so it cost nothing. */
    fromCache: z.boolean(),
    model: z.string().max(80).nullable(),
  })
  .strict();

export type Detection = z.infer<typeof detectionSchema>;

/** Whether a failed slide is worth sending again. */
export function isRetryable(detection: Detection | null): boolean {
  if (!detection) return true;
  if (detection.status !== "failed") return false;
  return detection.reason !== "invalid-response";
}

export const CONVERT_STATUSES = ["idle", "running", "done", "failed", "cancelled"] as const;

export const convertSchema = z
  .object({
    status: z.enum(CONVERT_STATUSES),
    /** Real Gemini requests this job has made, over all its runs. */
    calls: z.number().int().nonnegative(),
    /** Set once the file is on disk, so download knows it can serve it. */
    hasOutput: z.boolean(),
    error: z.string().max(200).nullable(),
    options: z
      .object({
        coverPatches: z.boolean(),
        dropWatermarks: z.boolean(),
        removeWatermark: z.boolean(),
      })
      .strict(),
    startedAt: z.number().int().nonnegative(),
    finishedAt: z.number().int().nonnegative(),
  })
  .strict();

export type Convert = z.infer<typeof convertSchema>;

export function newConvert(): Convert {
  return {
    status: "idle",
    calls: 0,
    hasOutput: false,
    error: null,
    options: { coverPatches: false, dropWatermarks: true, removeWatermark: true },
    startedAt: 0,
    finishedAt: 0,
  };
}

export const slideSchema = z
  .object({
    index: z.number().int().positive(),
    file: z.string().regex(/^\d{3}\.png$/),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
    // How the image was produced, so the Review page can explain quality later.
    origin: z.enum(["pptx-picture", "pdf-image", "pdf-render", "image"]),
    // The slide is not a single full-slide picture. T3 must keep its native
    // text and shapes instead of detecting them again.
    mixed: z.boolean(),
    hidden: z.boolean(),
    notes: z.boolean(),
    /** Null until this slide has been through detection at least once. */
    detection: detectionSchema.nullable(),
  })
  .strict();

/** job.json layout. Version 2 added per-slide detection and the conversion. */
export const JOB_VERSION = 2;

export const JOB_STATUSES = [
  "created",
  "uploading",
  "ready",
  "extracting",
  "done",
  "failed",
  "cancelled",
] as const;

export const jobSchema = z
  .object({
    version: z.literal(JOB_VERSION),
    id: jobIdSchema,
    status: z.enum(JOB_STATUSES),
    kind: z.enum(["pptx", "pdf", "images"]).nullable(),
    createdAt: z.number().int().positive(),
    updatedAt: z.number().int().positive(),
    files: z.array(sourceFileSchema).max(MAX_STORED_FILES),
    slides: z.array(slideSchema).max(MAX_STORED_SLIDES),
    done: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
    // A short English code, never a raw exception message.
    error: z.string().max(200).nullable(),
    convert: convertSchema,
  })
  .strict();

export type Job = z.infer<typeof jobSchema>;
export type Slide = z.infer<typeof slideSchema>;
export type SourceFile = z.infer<typeof sourceFileSchema>;

export function newJob(id: string, now: number): Job {
  return {
    version: JOB_VERSION,
    id,
    status: "created",
    kind: null,
    createdAt: now,
    updatedAt: now,
    files: [],
    slides: [],
    done: 0,
    total: 0,
    error: null,
    convert: newConvert(),
  };
}

/**
 * Version 1 files were written before T3, so they have no detection or
 * conversion state. They are upgraded in memory on read, which costs nothing
 * and keeps a job folder from an earlier run usable.
 */
export function upgradeJob(raw: unknown): unknown {
  if (typeof raw !== "object" || raw === null) return raw;
  const job = raw as Record<string, unknown>;
  if (job.version !== 1) return raw;
  const slides = Array.isArray(job.slides) ? job.slides : [];
  return {
    ...job,
    version: JOB_VERSION,
    slides: slides.map((slide) =>
      typeof slide === "object" && slide !== null ? { detection: null, ...slide } : slide,
    ),
    convert: newConvert(),
  };
}

const ALLOWED_NEXT: Record<Job["status"], ReadonlyArray<Job["status"]>> = {
  created: ["uploading", "failed", "cancelled"],
  uploading: ["uploading", "ready", "failed", "cancelled"],
  ready: ["extracting", "uploading", "failed", "cancelled"],
  extracting: ["done", "failed", "cancelled"],
  done: [],
  failed: [],
  cancelled: [],
};

export function canTransition(from: Job["status"], to: Job["status"]): boolean {
  return ALLOWED_NEXT[from].includes(to);
}
